# Generated by Django 4.2.3 on 2023-08-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_reginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reginfo',
            name='cpass',
        ),
        migrations.AlterField(
            model_name='reginfo',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
